using System;
using System.Data;

namespace Gribble.Model
{
    public class Column
    {
        public Column(
            string name, 
            Type type = null,
            SqlDbType sqlType = SqlDbType.NVarChar,
            int length = 0, 
            bool isNullable = false, 
            bool isIdentity = false, 
            bool isAutoGenerated = false, 
            bool isPrimaryKey = false, 
            bool isClusteredPrimaryKey = false,
            object defaultValue = null)
        {
            Name = name;
            Type = type;
            SqlType = sqlType;
            Length = length;
            IsIdentity = isIdentity;
            IsPrimaryKey = isPrimaryKey;
            Length = length;
            IsAutoGenerated = isAutoGenerated;
            IsNullable = isNullable;
            DefaultValue = defaultValue;
            IsClusteredPrimaryKey = isClusteredPrimaryKey;
        }

        public class OptionBuilder
        {
            private readonly Column _column;
            public OptionBuilder(Column column) { _column = column; }
            public Column Create() { return _column; }
            public OptionBuilder Length(int length) { _column.Length = length; return this; }
            public OptionBuilder Nullable() { _column.IsNullable = true; return this; }
            public OptionBuilder Identity() { _column.IsIdentity = true; return this; }
            public OptionBuilder AutoGenerated() { _column.IsAutoGenerated = true; return this; }
            public OptionBuilder PrimaryKey() { _column.IsPrimaryKey = true; return this; }
            public OptionBuilder ClusteredPrimaryKey() { _column.IsClusteredPrimaryKey = true; return this; }
            public static implicit operator Column(OptionBuilder builder) { return builder._column; }
        }

        public static OptionBuilder Create(string name, SqlDbType type)
        {
            return new OptionBuilder(new Column(name, sqlType: type));
        }

        public static OptionBuilder Create(string name, SqlDbType type, object defaultValue)
        {
            return new OptionBuilder(new Column(name, sqlType: type, defaultValue: defaultValue));
        }

        public static OptionBuilder Create<T>(string name)
        {
            return new OptionBuilder(new Column(name, typeof(T)));
        }

        public static OptionBuilder Create<T>(string name, T defaultValue)
        {
            return new OptionBuilder(new Column(name, typeof (T), defaultValue: defaultValue));
        }

        public static OptionBuilder Create(string name, Type type)
        {
            return new OptionBuilder(new Column(name, type));
        }

        public static OptionBuilder Create(string name, Type type, object defaultValue)
        {
            return new OptionBuilder(new Column(name, type, defaultValue: defaultValue));
        }

        public string Name { get; private set; }
        public Type Type { get; private set; }
        public SqlDbType SqlType { get; private set; }
        public int Length { get; private set; }
        public bool IsNullable { get; private set; }
        public bool IsIdentity { get; private set; }
        public bool IsAutoGenerated { get; private set; }
        public object DefaultValue { get; private set; }
        public bool IsPrimaryKey { get; private set; }
        public bool IsClusteredPrimaryKey { get; private set; }
    }
}
