using System;

namespace Gribble.Model
{
    public class Column
    {
        public Column(
            string name, 
            Type type, 
            int length = 0, 
            bool isNullable = false, 
            bool isIdentity = false, 
            bool isAutoGenerated = false, 
            bool isPrimaryKey = false, 
            object defaultValue = null)
        {
            Name = name;
            Type = type;
            Length = length;
            IsIdentity = isIdentity;
            IsPrimaryKey = isPrimaryKey;
            Length = length;
            IsAutoGenerated = isAutoGenerated;
            IsNullable = isNullable;
            DefaultValue = defaultValue;
        }

        public static Column Create<T>(
            string name,
            int length = 0,
            bool isNullable = false,
            bool isIdentity = false,
            bool isAutoGenerated = false,
            bool isPrimaryKey = false,
            T defaultValue = default(T))
        {
            return new Column(
                name,
                typeof(T),
                isIdentity: isIdentity,
                isPrimaryKey: isPrimaryKey,
                length: length,
                isAutoGenerated: isAutoGenerated,
                isNullable: isNullable,
                defaultValue: defaultValue);
        }

        public static Column Create<T>(
            string name,
            int length = 0,
            bool isNullable = false,
            bool isIdentity = false,
            bool isAutoGenerated = false,
            bool isPrimaryKey = false)
        {
            return new Column(
                name,
                typeof(T),
                isIdentity: isIdentity,
                isPrimaryKey: isPrimaryKey,
                length: length,
                isAutoGenerated: isAutoGenerated,
                isNullable: isNullable);
        }

        public string Name { get; private set; }
        public Type Type { get; private set; }
        public int Length { get; private set; }
        public bool IsNullable { get; private set; }
        public bool IsIdentity { get; private set; }
        public bool IsAutoGenerated { get; private set; }
        public object DefaultValue { get; private set; }
        public bool IsPrimaryKey { get; private set; }
    }
}
