using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Gribble;
using Gribble.Mapping;
using Gribble.Model;
using NUnit.Framework;
using Should;

namespace Tests
{
    [TestFixture]
    public class DatabaseTests
    {
        private static readonly TestDatabase Database =
            new TestDatabase("[id] [int] IDENTITY(1,1) NOT NULL, [name] [varchar] (500) NULL, [hide] [bit] NULL, [timestamp] [datetime] NULL",
                             10, "name, hide, [timestamp]", "'oh hai', 0, GETDATE()");

        public class Entity
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public Dictionary<string, object> Values { get; set; }
        }

        public class TestClassMap : ClassMap<Entity>
        {
            public TestClassMap()
            {
                Id(x => x.Id).Column("id");
                Map(x => x.Name).Column("name");
                Map(x => x.Values).Dynamic();
            }
        }

        public static EntityMappingCollection MappingCollection = new EntityMappingCollection(new IClassMap[] { new TestClassMap() });
        public static IProfiler Profiler = new ConsoleProfiler();
        public IDatabase GribbleDatabase;

        [TestFixtureSetUp]
        public void Setup()
        {
            Database.SetUp();
            Database.CreateTables();
            Database.ExecuteNonQuery("CREATE PROCEDURE GetAll AS BEGIN SELECT * FROM {0} END", Database.FirstTable.Name);
            Database.ExecuteNonQuery("CREATE PROCEDURE GetOne @Id int AS BEGIN SELECT TOP 1 * FROM {0} WHERE Id=@Id END", Database.FirstTable.Name);
            Database.ExecuteNonQuery("CREATE PROCEDURE GetCount AS BEGIN SELECT COUNT(*) FROM {0} END", Database.FirstTable.Name);
            Database.ExecuteNonQuery("CREATE PROCEDURE DeleteOne @Id int AS BEGIN DELETE FROM {0} WHERE Id=@Id END", Database.FirstTable.Name);
            GribbleDatabase = Gribble.Database.Create(new ConnectionManager(Database.Connection, TimeSpan.FromMinutes(5)), MappingCollection, Profiler);
        }

        [TestFixtureTearDown]
        public void TearDown() { Database.TearDown(); }

        [SetUp]
        public void TestSetup() { Database.CreateTables(); }

        [Test]
        public void Get_All_Test()
        {
            var results = GribbleDatabase.CallProcedureMany<Entity>("GetAll").ToList();
            results.Count().ShouldEqual(10);
            results.All(x => x.Name.Length > 3).ShouldEqual(true);
            results.All(x => x.Id > -1).ShouldEqual(true);
            results.First().Values.Count.ShouldEqual(2);
            ((bool)results.First().Values["hide"]).ShouldEqual(false);
            ((DateTime)results.First().Values["timestamp"]).ShouldBeGreaterThan(DateTime.MinValue);
        }

        [Test]
        public void Get_One_Test()
        {
            var result = GribbleDatabase.CallProcedureSingle<Entity>("GetOne", new Dictionary<string, object> { { "Id", 5 } });
            result.ShouldNotBeNull();
            result.Name.Length.ShouldBeGreaterThan(3);
            result.Id.ShouldEqual(5);
            result.Values.Count.ShouldEqual(2);
            ((bool)result.Values["hide"]).ShouldEqual(false);
            ((DateTime)result.Values["timestamp"]).ShouldBeGreaterThan(DateTime.MinValue);
        }

        [Test]
        public void Get_Scalar_Test()
        {
            var result = GribbleDatabase.CallProcedureScalar<int>("GetCount");
            result.ShouldBeGreaterThan(8);
        }

        [Test]
        public void Get_Non_Query_Test()
        {
            GribbleDatabase.CallProcedure("DeleteOne", new Dictionary<string, object> { { "Id", 6 } });

            var result = GribbleDatabase.CallProcedureScalar<int>("GetCount");
            result.ShouldEqual(9);
        }

        [Test]
        public void Create_Table_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            Gribble.Database.Create(new ConnectionManager(Database.Connection, TimeSpan.FromMinutes(5)), MappingCollection, Profiler).CreateTable(tableName,
                                    new Column("Id", typeof(Guid), key: Column.KeyType.PrimaryKey, isAutoGenerated: true),
                                    new Column("Name", typeof(string), isNullable: true, length: 500),
                                    new Column("Active", typeof(bool), isNullable: false, defaultValue: true),
                                    new Column("Score", typeof(decimal), isNullable: false, precision: 5, scale: 1),
                                    new Column("ScoreA", isNullable: false, computation: "Score * 55"),
                                    new Column("ScoreB", isNullable: false, computation: "Score * 55", computationPersisted: true),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.tables WHERE name='{0}'", tableName).ShouldEqual(1);
        }

        [Test]
        public void Create_Table_Identity_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey),
                new Column("Name", typeof(string), isNullable: true, length: 500),
                new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.tables WHERE name='{0}'", tableName).ShouldEqual(1);
        }

        [Test]
        public void Drop_Table_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey),
                                    new Column("Name", typeof(string), isNullable: true, length: 500),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.tables WHERE name='{0}'", tableName).ShouldEqual(1);

            GribbleDatabase.DeleteTable(tableName);

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.tables WHERE name='{0}'", tableName).ShouldEqual(0);
        }

        [Test]
        public void should_indicate_table_exists()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName, new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey));
            GribbleDatabase.TableExists(tableName).ShouldBeTrue();
        }

        [Test]
        public void should_indicate_table_does_not_exist()
        {
            GribbleDatabase.TableExists("yada").ShouldBeFalse();
        }

        [Test]
        public void should_get_table_columns()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.ClusteredPrimaryKey),
                                    new Column("Uid", typeof(Guid), isAutoGenerated: true),
                                    new Column("Name", typeof(string), isNullable: true, length: 500),
                                    new Column("Active", typeof(bool), defaultValue: true),
                                    new Column("Score", typeof(decimal), precision: 5, scale: 1),
                                    new Column("TotalScore", isNullable: false, computation: "Score * 55", computationPersisted: true),
                                    new Column("Created", typeof(DateTime), isAutoGenerated: true));

            var columns = GribbleDatabase.GetColumns(tableName).ToList();
            columns.Count.ShouldEqual(7);
            var column = columns[0];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeTrue();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.ClusteredPrimaryKey);
            column.Length.ShouldEqual((short)4);
            column.Name.ShouldEqual("Id");
            column.Precision.ShouldEqual((byte)10);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.Int);
            column.Type.ShouldEqual(typeof(int));

            column = columns[1];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeTrue();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)16);
            column.Name.ShouldEqual("Uid");
            column.Precision.ShouldEqual((byte)0);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.UniqueIdentifier);
            column.Type.ShouldEqual(typeof(Guid));

            column = columns[2];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeTrue();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)500);
            column.Name.ShouldEqual("Name");
            column.Precision.ShouldEqual((byte)0);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.NVarChar);
            column.Type.ShouldEqual(typeof(string));

            column = columns[3];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldEqual("1");
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)1);
            column.Name.ShouldEqual("Active");
            column.Precision.ShouldEqual((byte)1);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.Bit);
            column.Type.ShouldEqual(typeof(bool));

            column = columns[4];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)5);
            column.Name.ShouldEqual("Score");
            column.Precision.ShouldEqual((byte)5);
            column.Scale.ShouldEqual((byte)1);
            column.SqlType.ShouldEqual(SqlDbType.Decimal);
            column.Type.ShouldEqual(typeof(decimal));

            column = columns[5];
            column.Computation.ShouldEqual("([Score]*(55))");
            column.ComputationPersisted.Value.ShouldBeTrue();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeTrue();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)5);
            column.Name.ShouldEqual("TotalScore");
            column.Precision.ShouldEqual((byte)8);
            column.Scale.ShouldEqual((byte)1);
            column.SqlType.ShouldEqual(SqlDbType.Decimal);
            column.Type.ShouldEqual(typeof(decimal));

            column = columns[6];
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeTrue();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeTrue();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)8);
            column.Name.ShouldEqual("Created");
            column.Precision.ShouldEqual((byte)23);
            column.Scale.ShouldEqual((byte)3);
            column.SqlType.ShouldEqual(SqlDbType.DateTime);
            column.Type.ShouldEqual(typeof(DateTime));
        }

        [Test]
        public void should_add_table_columns()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.ClusteredPrimaryKey),
                                    new Column("Uid", typeof(Guid), isAutoGenerated: true),
                                    new Column("Created", typeof(DateTime), isAutoGenerated: true));

            GribbleDatabase.AddColumns(tableName,
                new Column("Uid", typeof(Guid), isAutoGenerated: true),
                new Column("Name", typeof(string), isNullable: true, length: 500));

            var columns = GribbleDatabase.GetColumns(tableName).ToList();

            columns.Count.ShouldEqual(4);
            var column = columns[0];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeTrue();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.ClusteredPrimaryKey);
            column.Length.ShouldEqual((short)4);
            column.Name.ShouldEqual("Id");
            column.Precision.ShouldEqual((byte)10);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.Int);
            column.Type.ShouldEqual(typeof(int));

            column = columns[1];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeTrue();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)16);
            column.Name.ShouldEqual("Uid");
            column.Precision.ShouldEqual((byte)0);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.UniqueIdentifier);
            column.Type.ShouldEqual(typeof(Guid));

            column = columns[2];
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeTrue();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeTrue();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeFalse();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)8);
            column.Name.ShouldEqual("Created");
            column.Precision.ShouldEqual((byte)23);
            column.Scale.ShouldEqual((byte)3);
            column.SqlType.ShouldEqual(SqlDbType.DateTime);
            column.Type.ShouldEqual(typeof(DateTime));

            column = columns[3];
            column.Computation.ShouldBeNull();
            column.ComputationPersisted.ShouldBeNull();
            column.DefaultValue.ShouldBeNull();
            column.IsAutoGenerated.ShouldBeFalse();
            column.IsComputed.ShouldBeFalse();
            column.IsIdentity.ShouldBeFalse();
            column.IsNullable.ShouldBeTrue();
            column.Key.ShouldEqual(Column.KeyType.None);
            column.Length.ShouldEqual((short)500);
            column.Name.ShouldEqual("Name");
            column.Precision.ShouldEqual((byte)0);
            column.Scale.ShouldEqual((byte)0);
            column.SqlType.ShouldEqual(SqlDbType.NVarChar);
            column.Type.ShouldEqual(typeof(string));
        }

        [Test]
        public void should_get_table_indexes()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.ClusteredPrimaryKey),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));
            GribbleDatabase.AddNonClusteredIndex(tableName, new Index.Column("Id"), new Index.Column("Created"));
            GribbleDatabase.AddNonClusteredIndex(tableName, new Index.Column("Created"));

            var indexes = GribbleDatabase.GetIndexes(tableName).ToList();
            indexes.Count.ShouldEqual(3);

            var index = indexes[2];
            index.Clustered.ShouldBeTrue();
            index.Columns.Count().ShouldEqual(1);
            index.Columns.First().Name.ShouldEqual("Id");
            index.Columns.First().Descending.ShouldBeFalse();
            index.Name.ShouldStartWith("PK_");
            index.Name.ShouldContain("_Id");
            index.PrimaryKey.ShouldBeTrue();
            index.Unique.ShouldBeTrue();

            index = indexes[1];
            index.Clustered.ShouldBeFalse();
            index.Columns.Count().ShouldEqual(2);
            index.Columns.First().Name.ShouldEqual("Id");
            index.Columns.First().Descending.ShouldBeFalse();
            index.Columns.Last().Name.ShouldEqual("Created");
            index.Columns.Last().Descending.ShouldBeFalse();
            index.Name.ShouldStartWith("IX_");
            index.Name.ShouldContain("_Id_Created");
            index.PrimaryKey.ShouldBeFalse();
            index.Unique.ShouldBeFalse();

            index = indexes[0];
            index.Clustered.ShouldBeFalse();
            index.Columns.Count().ShouldEqual(1);
            index.Columns.First().Name.ShouldEqual("Created");
            index.Columns.First().Descending.ShouldBeFalse();
            index.Name.ShouldStartWith("IX_");
            index.Name.ShouldContain("_Created");
            index.PrimaryKey.ShouldBeFalse();
            index.Unique.ShouldBeFalse();
        }

        [Test]
        public void should_add_table_indexes()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.ClusteredPrimaryKey),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));
            GribbleDatabase.AddNonClusteredIndex(tableName, new Index.Column("Id"), new Index.Column("Created"));
            GribbleDatabase.AddNonClusteredIndexes(tableName, new Index.ColumnSet { "Id", "Created" }, new Index.ColumnSet { "Created" }); 

            var indexes = GribbleDatabase.GetIndexes(tableName).ToList();
            indexes.Count.ShouldEqual(3);

            var index = indexes[2];
            index.Clustered.ShouldBeTrue();
            index.Columns.Count().ShouldEqual(1);
            index.Columns.First().Name.ShouldEqual("Id");
            index.Columns.First().Descending.ShouldBeFalse();
            index.Name.ShouldStartWith("PK_");
            index.Name.ShouldContain("_Id");
            index.PrimaryKey.ShouldBeTrue();
            index.Unique.ShouldBeTrue();

            index = indexes[1];
            index.Clustered.ShouldBeFalse();
            index.Columns.Count().ShouldEqual(2);
            index.Columns.First().Name.ShouldEqual("Id");
            index.Columns.First().Descending.ShouldBeFalse();
            index.Columns.Last().Name.ShouldEqual("Created");
            index.Columns.Last().Descending.ShouldBeFalse();
            index.Name.ShouldStartWith("IX_");
            index.Name.ShouldContain("_Id_Created");
            index.PrimaryKey.ShouldBeFalse();
            index.Unique.ShouldBeFalse();

            index = indexes[0];
            index.Clustered.ShouldBeFalse();
            index.Columns.Count().ShouldEqual(1);
            index.Columns.First().Name.ShouldEqual("Created");
            index.Columns.First().Descending.ShouldBeFalse();
            index.Name.ShouldStartWith("IX_");
            index.Name.ShouldContain("_Created");
            index.PrimaryKey.ShouldBeFalse();
            index.Unique.ShouldBeFalse();
        }

        [Test]
        public void Add_Column_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.columns WHERE name='Name' and object_id('{0}') = object_id", tableName).ShouldEqual(0);

            GribbleDatabase.AddColumn(tableName, 
                                    new Column("Name", typeof(string), isNullable: true, length: 500));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.columns WHERE name='Name' and object_id('{0}') = object_id", tableName).ShouldEqual(1);
        }

        [Test]
        public void Drop_Column_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey),
                                    new Column("Name", typeof(string), isNullable: true, length: 500),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.columns WHERE name='Name' and object_id('{0}') = object_id", tableName).ShouldEqual(1);

            GribbleDatabase.RemoveColumn(tableName, "Name");

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.columns WHERE name='Name' and object_id('{0}') = object_id", tableName).ShouldEqual(0);
        }

        [Test]
        public void Add_Index_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey),
                                    new Column("Name", typeof(string), isNullable: true, length: 500),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.indexes WHERE name='IX_{0}_Name_Created' and object_id('{0}') = object_id", tableName).ShouldEqual(0);

            GribbleDatabase.AddNonClusteredIndex(tableName, new Index.Column("Name"), new Index.Column("Created"));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.indexes WHERE name='IX_{0}_Name_Created' and object_id('{0}') = object_id", tableName).ShouldEqual(1);
        }

        [Test]
        public void Drop_Index_Test()
        {
            var tableName = "Temp" + Guid.NewGuid().ToString("N");
            GribbleDatabase.CreateTable(tableName,
                                    new Column("Id", typeof(int), isIdentity: true, key: Column.KeyType.PrimaryKey),
                                    new Column("Name", typeof(string), isNullable: true, length: 500),
                                    new Column("Created", typeof(DateTime), isNullable: false, isAutoGenerated: true));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.indexes WHERE name='IX_{0}_Name_Created' and object_id('{0}') = object_id", tableName).ShouldEqual(0);

            GribbleDatabase.AddNonClusteredIndex(tableName, new Index.Column("Name"), new Index.Column("Created"));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.indexes WHERE name='IX_{0}_Name_Created' and object_id('{0}') = object_id", tableName).ShouldEqual(1);

            GribbleDatabase.RemoveNonClusteredIndex(tableName, string.Format("IX_{0}_Name_Created", tableName));

            Database.ExecuteScalar<int>("SELECT COUNT(*) FROM sys.indexes WHERE name='IX_{0}_Name_Created' and object_id('{0}') = object_id", tableName).ShouldEqual(0);
        }
    }
}
